<?php 
require_once 'includes/db.php'; 
include 'includes/header.php'; 
?>

    <header class="heroSection">
        <div class="heroBgContainer">
            <img src="./img/brand/imgSocialMedia.webp" class="heroImg" alt="Image de fond de la section">
        </div>
        <div class="heroContent">
            <h1 class="heroTitleAPropos">Qui sommes-nous ?</h1>
            <p class="heroSubtitle">no waste, just taste.</p>
        </div>
    </header>

    <section class="presentationBrand">
        <h2 class="titlePresentationBrand">RESIDUE_ EST. 2024</h2>
        <h3 class="subtitlePresentationBrand">BASED IN PARIS — LISBONNE.</h3>
        <p>CRÉER UN MOUVEMENT BRUTALISTE, INSPIRER UNE NOUVELLE VISION DU LUXE À TRAVERS LE PRISME DE L'INDUSTRIEL.<br>

            NOTRE PHILOSOPHIE DE MARQUE REPOSE SUR L'IDÉE DE "THINKING RAW". NOUS COMPRENONS CETTE PENSÉE BRUTE COMME UN SYNONYME DE 
            "VOIR L'INVISIBLE". CELA SIGNIFIE AVOIR UN ESPRIT CRITIQUE QUI VA AU-DELÀ DE LA SURFACE, QUI REFUSE LA FACILITÉ DU NEUF POUR 
            ACCUEILLIR LE POTENTIEL DE CE QUI A ÉTÉ LAISSÉ POUR COMPTE.<br><br>

            C'EST UN ÉTAT D'ESPRIT QUI DÉCLENCHE L'INNOVATION ET NOURRIT L'AMBITION. IL EXIGE DE DÉFIER LE STATUS QUO DE LA SURPRODUCTION ET 
            LES CONVENTIONS DE LA FAST FASHION, EN REPOUSSANT LES LIMITES DE CE QUE NOUS CROYONS ÊTRE UN "DÉCHET". NOUS AVONS LE POUVOIR D'ALLUMER 
            UNE ÉTINCELLE CHEZ CEUX QUI CHERCHENT DU SENS ET DE RASSEMBLER DES INDIVIDUS PARTAGEANT LES MÊMES IDÉES POUR COLLABORER VERS UN BUT 
            COMMUN : LA REVALORISATION RADICALE.<br><br>

            NOTRE OBJECTIF EST D'INSPIRER L'AUDACE ET LA SUBSTANCE. NOUS VOULONS ENCOURAGER NOTRE COMMUNAUTÉ À REGARDER SON 
            ENVIRONNEMENT DIFFÉREMMENT. NOUS OFFRONS DES OPPORTUNITÉS AUX DESIGNERS, ARTISANS ET CRÉATEURS DE DÉMONTRER QUE LA CONTRAINTE 
            DE LA MATIÈRE EST LE PLUS PUISSANT MOTEUR DE CRÉATIVITÉ.<br><br>

            NOUS EMBRASSONS L'ÉNERGIE INDUSTRIELLE ET L'EXPRESSION ARCHITECTURALE. NOUS CROYONS QUE LA CRÉATIVITÉ NE S'EXPRIME PAS SEULEMENT 
            À TRAVERS L'ART, MAIS INFLUENCE AUSSI LA RÉSOLUTION DE PROBLÈMES, L'INNOVATION DURABLE, L'ENTREPRENEURIAT, LA PENSÉE CRITIQUE 
            ET LE CHANGEMENT SOCIAL.<br><br>

            L'ÉNERGIE DE RESIDUE_ ENCOURAGE NOTRE COMMUNAUTÉ À EXPRIMER SON IDENTITÉ DISTINCTE, CÉLÉBRANT CE QUI LES SÉPARE DE LA FOULE 
            STANDARDISÉE. CETTE ÉNERGIE LIBÈRE LES INDIVIDUS DE LA CONFORMITÉ DE L'ÉPHÉMÈRE. NOUS CONSTRUISONS DES ARCHIVES, 
            PAS DES COLLECTIONS.<br><br>

            NOUS VOULONS ÊTRE UNE PLATEFORME DE PARTAGE ET D'INSPIRATION. DONNER AUX INDIVIDUS LES OUTILS DONT ILS ONT BESOIN POUR COMPRENDRE 
            CE QU'ILS PORTENT. NOUS VOULONS ÊTRE UN NARRATEUR VISUEL, RACONTANT L'HISTOIRE DU BÉTON, DE LA MATIÈRE ET DE L'ESPRIT DE CHAQUE 
            STRUCTURE URBAINE.<br><br>

            DES FRICHES INDUSTRIELLES DE LA BANLIEUE PARISIENNE AUX FAÇADES MINÉRALES DE LISBONNE, CHAQUE PAYSAGE URBAIN INCARNE 
            UNE ÂME STREETWEAR DISTINCTE. DANS CE RÉCIT, NOUS NOUS LANÇONS DANS UN VOYAGE D'EXPLORATION, MONTRANT COMMENT LE VÊTEMENT 
            REFLÈTE LE POULS DES VILLES ET INFLUENCE UNE COMMUNAUTÉ MONDIALE DE PASSIONNÉS DE DESIGN FONCTIONNEL.<br><br>

            LE RESPECT ET L'APPRÉCIATION POUR LE SAVOIR-FAIRE FRANÇAIS SONT AU CŒUR DE NOS DESIGNS. CHAQUE PIÈCE EST UNE DÉCLARATION 
            D'AMOUR À L'ARTISANAT LOCAL, FAÇONNÉE DANS DES COTONS LOURDS QUI TRAVERSERONT LES ÉPOQUES.<br><br>

            INSPIRER LES AUTRES ET BÂTIR UN MOUVEMENT MONDIAL. CRÉER UN HÉRITAGE INTERNATIONAL INSPIRÉ PAR LA MÉMOIRE DE LA MATIÈRE.<br><br>

            NO WASTE, JUST TASTE.
        </p>

    </section>

<?php include 'includes/footer.php'; ?>